---
title: "Delineamento de Experimentos"
subtitle: "Uso de sobredoses de vitamina B12 na diminuição de aterosclerose, em pacientes com a doença."
author:  "Jonatha Azevedo/Leonardo Filgueira"
date: "`r format(Sys.Date(),'%d de %B de %Y')`"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---






## Introdução

A aterosclerose é caracterizada pela formação de placas de gordura e tecido fibroso nas paredes internas das artérias, causando obstruções que impedem o fluxo sanguíneo. Trata-se da principal causa de infartos, acidentes vasculares e doença arterial periférica.

Capaz de afetar qualquer artéria do corpo, a condição tem início durante a infância/juventude e piora com o tempo. É assintomática durante a maior parte do seu desenvolvimento e muitas vezes só é descoberta após o surgimento de alguma complicação

## Objetivos


Temos o objetivo de identificar se é estatisticamente significante o uso de sobredoses de vitamina B12 para diminuição da aterosclerose (nossa variável resposta). Logo, nosso experimento tenta identificar se o uso de sobredose de vitamina B12 aumenta o diâmetro da artéria (em mm), já que a doença faz com que essas artérias entupam com o progresso da doença.

## Metodologia 

Propomos um trabalho com a diferença entre os diâmetros das artérias entre o início do tratamento e depois das unidades experimentais terem sido submetidas ao tratamento com a sobredose de vitamina B12. Logo, qualquer aumento de diâmetro após o tratamento é considerado um bom resultado para o experimento realizado.



  - Unidade experimental: Paciente com a doença.
  - Variável resposta: diminuição da aterosclerose (diâmetro do calibre em mm)
  - Tratamentos em comparação (níveis): dose padrão, sobredose média e alta
  - Designação dos tratamentos: por sorteio
  - Número de repetições: 12 doentes por tratamento
