---
title: "Delineamento de Experimentos em Blocos"
subtitle: "Serviços de entrega"
author:  "Jonatha Azevedo/Leonardo Filgueira"
date: "`r format(Sys.Date(),'%d de %B de %Y')`"
output: word_document
---

## Introdução

Cosidere uma empresa que regularmente tem que enviar encomendas entre suas 4 filiais e tem a opção de usar quatro serviços concorrentes de entrega de encomendas, os quais cobram valores semelhantes para realizar a entrega. Nesta situação é razoável que se escolha a transportadora que entregue as encomendas com o menor tempo.

## Objetivos
  
Determinar qual serviço de entrega usar, baseando-se no tempo de entrega das encomendas.

## Metodologia 

Propomos um experimento enviando pacotes da matriz da empresa para cada um das quatro filiais, utilizando 4 serviços de transportadora, contabilizando o tempo de entrega de cada pacote. 

O experimento foi realizado utilizando a divisão de filiais como blocos, já que o serviço de entregas a ser contratado será utilizado para que todas as 4 filiais recebam encomendas. O fato de as 4 filiais estarem localizadas em regiões geográficas diferentes exige a divisão em blocos para que obtenha-se resultado com menor chance de erro.

  - Unidade experimental: efetuar a entrega dos pacotes .
  - Variável resposta: Tempo de entrega (em horas).
  - Tratamentos em comparação: Transportadoras.
  - Blocos: Filiais
  - Designação dos tratamentos: por sorteio.
  - Número de repetições: 30 encomendas por filial e por bloco.

Nessa metogologia, estamos considerando o uso de blocos aleatorizados buscando obter o máximo de homogeneidade dentro dos grupos e heterogeneidade entre os grupos.

### Variáveis

- **Variável resposta:** Tempo de entrega (em horas).

- **Fator**: serviço de entrega.
    - **Níveis:**
        - ``Serviço 1``;
        - ``Serviço 2``;
        - ``Serviço 3``;
        - ``Serviço 4``.

### Dados

Após a obtenção dos dados, estes foram armazenados numa tabela, cujas primeiras linhas são mostradas a seguir: 

```{r echo = F, warning=F, message=F}
if(require(pacman)){
  p_load(ggplot2, tidyverse, data.table)
}else{
  install.packages("pacman")
  pacman::p_load(ggplot2, tidyverse, data.table)
}

set.seed(1)

delivery_df = tibble(
  Transp = c(rep("Serviço 1", 30*4), rep("Serviço 2", 30*4),
              rep("Serviço 3", 30*4), rep("Serviço 4",30*4)),
  Destino = c(rep(c("Filial 1", "Filial 2", "Filial 3",
                    "Filial 4"), 30*4))
) %>% 
  arrange(Transp, Destino)

media_glob <- 5

nvl_1 <- media_glob + round(rnorm(120, 2.5, 0.25), 2)
nvl_2 <- media_glob + round(rnorm(120, 0, 0.25), 2)
nvl_3 <- media_glob + round(rnorm(120, -0.5, 0.25), 2)
nvl_4 <- media_glob + round(rnorm(120, 0, 0.25), 2)

tempos <- c(nvl_1, nvl_2, nvl_3, nvl_4)

delivery_df$tempo <- tempos

delivery_df <- data.table(delivery_df)

delivery_df[Destino %in% c("Filial 1", "Filial 2"), tempo := tempo + rnorm(60, 0.5, 0.1)]
delivery_df[Destino %in% c("Filial 3", "Filial 4"), tempo := tempo + rnorm(60, 1, 0.15)]

knitr::kable(head(delivery_df), row.names = F, 
              col.names = c("Transportadora", "Filial", "Tempo (em horas)"))
```

